// <auto-generated />
using System;
using Dispractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dispractice.Migrations
{
    [DbContext(typeof(MilitaryServiceContext))]
    [Migration("20250424214238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Dispractice.Models.Commendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwardedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicemanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServicemanId");

                    b.ToTable("Commendations");
                });

            modelBuilder.Entity("Dispractice.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommendationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExecuted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRemoved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OffenseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicemanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommendationId");

                    b.HasIndex("ServicemanId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Dispractice.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Dispractice.Models.Serviceman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNaval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronomic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceStartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Servicemans");
                });

            modelBuilder.Entity("Dispractice.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Воинская часть"
                        });
                });

            modelBuilder.Entity("Dispractice.Models.Commendation", b =>
                {
                    b.HasOne("Dispractice.Models.Serviceman", "Serviceman")
                        .WithMany("Commendations")
                        .HasForeignKey("ServicemanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serviceman");
                });

            modelBuilder.Entity("Dispractice.Models.Penalty", b =>
                {
                    b.HasOne("Dispractice.Models.Commendation", "Commendation")
                        .WithMany()
                        .HasForeignKey("CommendationId");

                    b.HasOne("Dispractice.Models.Serviceman", "Serviceman")
                        .WithMany("Penalties")
                        .HasForeignKey("ServicemanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commendation");

                    b.Navigation("Serviceman");
                });

            modelBuilder.Entity("Dispractice.Models.Position", b =>
                {
                    b.HasOne("Dispractice.Models.Unit", "Unit")
                        .WithMany("Positions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Dispractice.Models.Serviceman", b =>
                {
                    b.HasOne("Dispractice.Models.Position", "Position")
                        .WithOne("Serviceman")
                        .HasForeignKey("Dispractice.Models.Serviceman", "PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Dispractice.Models.Unit", b =>
                {
                    b.HasOne("Dispractice.Models.Unit", "ParentUnit")
                        .WithMany("SubUnits")
                        .HasForeignKey("ParentUnitId");

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("Dispractice.Models.Position", b =>
                {
                    b.Navigation("Serviceman");
                });

            modelBuilder.Entity("Dispractice.Models.Serviceman", b =>
                {
                    b.Navigation("Commendations");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("Dispractice.Models.Unit", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("SubUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
